// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pb/sql/sql.proto

package sql

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	descriptor "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Order is a sort order.
type SortCriteria_Order int32

const (
	// ascending sort order
	SortCriteria_ASC SortCriteria_Order = 0
	// descending sort order
	SortCriteria_DESC SortCriteria_Order = 1
)

var SortCriteria_Order_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}

var SortCriteria_Order_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x SortCriteria_Order) String() string {
	return proto.EnumName(SortCriteria_Order_name, int32(x))
}

func (SortCriteria_Order) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f3cfc32bb50cc571, []int{5, 0}
}

type Filter_Mode int32

const (
	// EQ in sql =
	Filter_EQ Filter_Mode = 0
	// NE  in sql !=
	Filter_NE Filter_Mode = 1
	// GT in sql >
	Filter_GT Filter_Mode = 2
	// GE in sql >=
	Filter_GE Filter_Mode = 3
	// LT in sql <
	Filter_LT Filter_Mode = 4
	// LE in sql <=
	Filter_LE Filter_Mode = 5
	// IS_NULL in sql IS NULL
	Filter_IS_NULL Filter_Mode = 6
	// NOT_NULL in sql IS NOT NULL
	Filter_NOT_NULL Filter_Mode = 7
)

var Filter_Mode_name = map[int32]string{
	0: "EQ",
	1: "NE",
	2: "GT",
	3: "GE",
	4: "LT",
	5: "LE",
	6: "IS_NULL",
	7: "NOT_NULL",
}

var Filter_Mode_value = map[string]int32{
	"EQ":       0,
	"NE":       1,
	"GT":       2,
	"GE":       3,
	"LT":       4,
	"LE":       5,
	"IS_NULL":  6,
	"NOT_NULL": 7,
}

func (x Filter_Mode) String() string {
	return proto.EnumName(Filter_Mode_name, int32(x))
}

func (Filter_Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f3cfc32bb50cc571, []int{7, 0}
}

type ExtraField struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tags                 string   `protobuf:"bytes,3,opt,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtraField) Reset()         { *m = ExtraField{} }
func (m *ExtraField) String() string { return proto.CompactTextString(m) }
func (*ExtraField) ProtoMessage()    {}
func (*ExtraField) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3cfc32bb50cc571, []int{0}
}
func (m *ExtraField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtraField.Unmarshal(m, b)
}
func (m *ExtraField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtraField.Marshal(b, m, deterministic)
}
func (m *ExtraField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtraField.Merge(m, src)
}
func (m *ExtraField) XXX_Size() int {
	return xxx_messageInfo_ExtraField.Size(m)
}
func (m *ExtraField) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtraField.DiscardUnknown(m)
}

var xxx_messageInfo_ExtraField proto.InternalMessageInfo

func (m *ExtraField) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ExtraField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExtraField) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

type SqlxMessageOptions struct {
	Orm                  bool          `protobuf:"varint,1,opt,name=orm,proto3" json:"orm,omitempty"`
	Jsonb                bool          `protobuf:"varint,2,opt,name=jsonb,proto3" json:"jsonb,omitempty"`
	Gorm                 bool          `protobuf:"varint,3,opt,name=gorm,proto3" json:"gorm,omitempty"`
	Table                string        `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"`
	Driver               string        `protobuf:"bytes,5,opt,name=driver,proto3" json:"driver,omitempty"`
	Include              []*ExtraField `protobuf:"bytes,6,rep,name=include,proto3" json:"include,omitempty"`
	Request              string        `protobuf:"bytes,7,opt,name=request,proto3" json:"request,omitempty"`
	User                 bool          `protobuf:"varint,8,opt,name=user,proto3" json:"user,omitempty"`
	Product              bool          `protobuf:"varint,9,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SqlxMessageOptions) Reset()         { *m = SqlxMessageOptions{} }
func (m *SqlxMessageOptions) String() string { return proto.CompactTextString(m) }
func (*SqlxMessageOptions) ProtoMessage()    {}
func (*SqlxMessageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3cfc32bb50cc571, []int{1}
}
func (m *SqlxMessageOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqlxMessageOptions.Unmarshal(m, b)
}
func (m *SqlxMessageOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqlxMessageOptions.Marshal(b, m, deterministic)
}
func (m *SqlxMessageOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqlxMessageOptions.Merge(m, src)
}
func (m *SqlxMessageOptions) XXX_Size() int {
	return xxx_messageInfo_SqlxMessageOptions.Size(m)
}
func (m *SqlxMessageOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_SqlxMessageOptions.DiscardUnknown(m)
}

var xxx_messageInfo_SqlxMessageOptions proto.InternalMessageInfo

func (m *SqlxMessageOptions) GetOrm() bool {
	if m != nil {
		return m.Orm
	}
	return false
}

func (m *SqlxMessageOptions) GetJsonb() bool {
	if m != nil {
		return m.Jsonb
	}
	return false
}

func (m *SqlxMessageOptions) GetGorm() bool {
	if m != nil {
		return m.Gorm
	}
	return false
}

func (m *SqlxMessageOptions) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *SqlxMessageOptions) GetDriver() string {
	if m != nil {
		return m.Driver
	}
	return ""
}

func (m *SqlxMessageOptions) GetInclude() []*ExtraField {
	if m != nil {
		return m.Include
	}
	return nil
}

func (m *SqlxMessageOptions) GetRequest() string {
	if m != nil {
		return m.Request
	}
	return ""
}

func (m *SqlxMessageOptions) GetUser() bool {
	if m != nil {
		return m.User
	}
	return false
}

func (m *SqlxMessageOptions) GetProduct() bool {
	if m != nil {
		return m.Product
	}
	return false
}

type SqlxFieldOptions struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Colname              string   `protobuf:"bytes,2,opt,name=colname,proto3" json:"colname,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Tags                 string   `protobuf:"bytes,4,opt,name=tags,proto3" json:"tags,omitempty"`
	Drop                 bool     `protobuf:"varint,5,opt,name=drop,proto3" json:"drop,omitempty"`
	Pk                   bool     `protobuf:"varint,6,opt,name=pk,proto3" json:"pk,omitempty"`
	Fk                   string   `protobuf:"bytes,7,opt,name=fk,proto3" json:"fk,omitempty"`
	Customname           string   `protobuf:"bytes,8,opt,name=customname,proto3" json:"customname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SqlxFieldOptions) Reset()         { *m = SqlxFieldOptions{} }
func (m *SqlxFieldOptions) String() string { return proto.CompactTextString(m) }
func (*SqlxFieldOptions) ProtoMessage()    {}
func (*SqlxFieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3cfc32bb50cc571, []int{2}
}
func (m *SqlxFieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqlxFieldOptions.Unmarshal(m, b)
}
func (m *SqlxFieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqlxFieldOptions.Marshal(b, m, deterministic)
}
func (m *SqlxFieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqlxFieldOptions.Merge(m, src)
}
func (m *SqlxFieldOptions) XXX_Size() int {
	return xxx_messageInfo_SqlxFieldOptions.Size(m)
}
func (m *SqlxFieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_SqlxFieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_SqlxFieldOptions proto.InternalMessageInfo

func (m *SqlxFieldOptions) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SqlxFieldOptions) GetColname() string {
	if m != nil {
		return m.Colname
	}
	return ""
}

func (m *SqlxFieldOptions) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SqlxFieldOptions) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *SqlxFieldOptions) GetDrop() bool {
	if m != nil {
		return m.Drop
	}
	return false
}

func (m *SqlxFieldOptions) GetPk() bool {
	if m != nil {
		return m.Pk
	}
	return false
}

func (m *SqlxFieldOptions) GetFk() string {
	if m != nil {
		return m.Fk
	}
	return ""
}

func (m *SqlxFieldOptions) GetCustomname() string {
	if m != nil {
		return m.Customname
	}
	return ""
}

type SqlxServiceOptions struct {
	Autogen              bool     `protobuf:"varint,1,opt,name=autogen,proto3" json:"autogen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SqlxServiceOptions) Reset()         { *m = SqlxServiceOptions{} }
func (m *SqlxServiceOptions) String() string { return proto.CompactTextString(m) }
func (*SqlxServiceOptions) ProtoMessage()    {}
func (*SqlxServiceOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3cfc32bb50cc571, []int{3}
}
func (m *SqlxServiceOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqlxServiceOptions.Unmarshal(m, b)
}
func (m *SqlxServiceOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqlxServiceOptions.Marshal(b, m, deterministic)
}
func (m *SqlxServiceOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqlxServiceOptions.Merge(m, src)
}
func (m *SqlxServiceOptions) XXX_Size() int {
	return xxx_messageInfo_SqlxServiceOptions.Size(m)
}
func (m *SqlxServiceOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_SqlxServiceOptions.DiscardUnknown(m)
}

var xxx_messageInfo_SqlxServiceOptions proto.InternalMessageInfo

func (m *SqlxServiceOptions) GetAutogen() bool {
	if m != nil {
		return m.Autogen
	}
	return false
}

type SqlxMethodOptions struct {
	Jsonb                bool     `protobuf:"varint,1,opt,name=jsonb,proto3" json:"jsonb,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SqlxMethodOptions) Reset()         { *m = SqlxMethodOptions{} }
func (m *SqlxMethodOptions) String() string { return proto.CompactTextString(m) }
func (*SqlxMethodOptions) ProtoMessage()    {}
func (*SqlxMethodOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3cfc32bb50cc571, []int{4}
}
func (m *SqlxMethodOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqlxMethodOptions.Unmarshal(m, b)
}
func (m *SqlxMethodOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqlxMethodOptions.Marshal(b, m, deterministic)
}
func (m *SqlxMethodOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqlxMethodOptions.Merge(m, src)
}
func (m *SqlxMethodOptions) XXX_Size() int {
	return xxx_messageInfo_SqlxMethodOptions.Size(m)
}
func (m *SqlxMethodOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_SqlxMethodOptions.DiscardUnknown(m)
}

var xxx_messageInfo_SqlxMethodOptions proto.InternalMessageInfo

func (m *SqlxMethodOptions) GetJsonb() bool {
	if m != nil {
		return m.Jsonb
	}
	return false
}

// SortCriteria represents sort criteria
type SortCriteria struct {
	// Tag is a JSON tag.
	Tag                  string             `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Order                SortCriteria_Order `protobuf:"varint,2,opt,name=order,proto3,enum=sql.SortCriteria_Order" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SortCriteria) Reset()         { *m = SortCriteria{} }
func (m *SortCriteria) String() string { return proto.CompactTextString(m) }
func (*SortCriteria) ProtoMessage()    {}
func (*SortCriteria) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3cfc32bb50cc571, []int{5}
}
func (m *SortCriteria) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SortCriteria.Unmarshal(m, b)
}
func (m *SortCriteria) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SortCriteria.Marshal(b, m, deterministic)
}
func (m *SortCriteria) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SortCriteria.Merge(m, src)
}
func (m *SortCriteria) XXX_Size() int {
	return xxx_messageInfo_SortCriteria.Size(m)
}
func (m *SortCriteria) XXX_DiscardUnknown() {
	xxx_messageInfo_SortCriteria.DiscardUnknown(m)
}

var xxx_messageInfo_SortCriteria proto.InternalMessageInfo

func (m *SortCriteria) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *SortCriteria) GetOrder() SortCriteria_Order {
	if m != nil {
		return m.Order
	}
	return SortCriteria_ASC
}

// Sorting represents list of sort criterias.
type Sorting struct {
	Sort                 []*SortCriteria `protobuf:"bytes,1,rep,name=sort,proto3" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Sorting) Reset()         { *m = Sorting{} }
func (m *Sorting) String() string { return proto.CompactTextString(m) }
func (*Sorting) ProtoMessage()    {}
func (*Sorting) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3cfc32bb50cc571, []int{6}
}
func (m *Sorting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sorting.Unmarshal(m, b)
}
func (m *Sorting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sorting.Marshal(b, m, deterministic)
}
func (m *Sorting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sorting.Merge(m, src)
}
func (m *Sorting) XXX_Size() int {
	return xxx_messageInfo_Sorting.Size(m)
}
func (m *Sorting) XXX_DiscardUnknown() {
	xxx_messageInfo_Sorting.DiscardUnknown(m)
}

var xxx_messageInfo_Sorting proto.InternalMessageInfo

func (m *Sorting) GetSort() []*SortCriteria {
	if m != nil {
		return m.Sort
	}
	return nil
}

type Filter struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mode                 Filter_Mode `protobuf:"varint,2,opt,name=mode,proto3,enum=sql.Filter_Mode" json:"mode,omitempty"`
	Value                string      `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3cfc32bb50cc571, []int{7}
}
func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Filter) GetMode() Filter_Mode {
	if m != nil {
		return m.Mode
	}
	return Filter_EQ
}

func (m *Filter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PageInfo struct {
	Current int64 `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	// The service may optionally include the total number of resources being paged.
	Size_ int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// The service may optionally include the offset of the next page of resources.
	// A null value indicates no more pages.
	Offset               int64    `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageInfo) Reset()         { *m = PageInfo{} }
func (m *PageInfo) String() string { return proto.CompactTextString(m) }
func (*PageInfo) ProtoMessage()    {}
func (*PageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3cfc32bb50cc571, []int{8}
}
func (m *PageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageInfo.Unmarshal(m, b)
}
func (m *PageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageInfo.Marshal(b, m, deterministic)
}
func (m *PageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageInfo.Merge(m, src)
}
func (m *PageInfo) XXX_Size() int {
	return xxx_messageInfo_PageInfo.Size(m)
}
func (m *PageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PageInfo proto.InternalMessageInfo

func (m *PageInfo) GetCurrent() int64 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *PageInfo) GetSize_() int64 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *PageInfo) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *PageInfo) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Query struct {
	Id  string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ids []string `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	// Types that are valid to be assigned to Params:
	//	*Query_Page
	//	*Query_First
	//	*Query_Last
	Params               isQuery_Params `protobuf_oneof:"params"`
	Limit                int64          `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Filter               []*Filter      `protobuf:"bytes,7,rep,name=filter,proto3" json:"filter,omitempty"`
	Field                []string       `protobuf:"bytes,8,rep,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3cfc32bb50cc571, []int{9}
}
func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

type isQuery_Params interface {
	isQuery_Params()
}

type Query_Page struct {
	Page int64 `protobuf:"varint,3,opt,name=page,proto3,oneof" json:"page,omitempty"`
}
type Query_First struct {
	First int64 `protobuf:"varint,4,opt,name=first,proto3,oneof" json:"first,omitempty"`
}
type Query_Last struct {
	Last int64 `protobuf:"varint,5,opt,name=last,proto3,oneof" json:"last,omitempty"`
}

func (*Query_Page) isQuery_Params()  {}
func (*Query_First) isQuery_Params() {}
func (*Query_Last) isQuery_Params()  {}

func (m *Query) GetParams() isQuery_Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Query) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Query) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *Query) GetPage() int64 {
	if x, ok := m.GetParams().(*Query_Page); ok {
		return x.Page
	}
	return 0
}

func (m *Query) GetFirst() int64 {
	if x, ok := m.GetParams().(*Query_First); ok {
		return x.First
	}
	return 0
}

func (m *Query) GetLast() int64 {
	if x, ok := m.GetParams().(*Query_Last); ok {
		return x.Last
	}
	return 0
}

func (m *Query) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Query) GetFilter() []*Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *Query) GetField() []string {
	if m != nil {
		return m.Field
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Query) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Query_Page)(nil),
		(*Query_First)(nil),
		(*Query_Last)(nil),
	}
}

type Response struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3cfc32bb50cc571, []int{10}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ResponseList struct {
	Data                 [][]byte  `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total                int64     `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	PageInfo             *PageInfo `protobuf:"bytes,3,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResponseList) Reset()         { *m = ResponseList{} }
func (m *ResponseList) String() string { return proto.CompactTextString(m) }
func (*ResponseList) ProtoMessage()    {}
func (*ResponseList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3cfc32bb50cc571, []int{11}
}
func (m *ResponseList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseList.Unmarshal(m, b)
}
func (m *ResponseList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseList.Marshal(b, m, deterministic)
}
func (m *ResponseList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseList.Merge(m, src)
}
func (m *ResponseList) XXX_Size() int {
	return xxx_messageInfo_ResponseList.Size(m)
}
func (m *ResponseList) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseList.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseList proto.InternalMessageInfo

func (m *ResponseList) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ResponseList) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ResponseList) GetPageInfo() *PageInfo {
	if m != nil {
		return m.PageInfo
	}
	return nil
}

type MutationField struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MutationField) Reset()         { *m = MutationField{} }
func (m *MutationField) String() string { return proto.CompactTextString(m) }
func (*MutationField) ProtoMessage()    {}
func (*MutationField) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3cfc32bb50cc571, []int{12}
}
func (m *MutationField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutationField.Unmarshal(m, b)
}
func (m *MutationField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutationField.Marshal(b, m, deterministic)
}
func (m *MutationField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutationField.Merge(m, src)
}
func (m *MutationField) XXX_Size() int {
	return xxx_messageInfo_MutationField.Size(m)
}
func (m *MutationField) XXX_DiscardUnknown() {
	xxx_messageInfo_MutationField.DiscardUnknown(m)
}

var xxx_messageInfo_MutationField proto.InternalMessageInfo

func (m *MutationField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MutationField) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type MutationResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MutationResponse) Reset()         { *m = MutationResponse{} }
func (m *MutationResponse) String() string { return proto.CompactTextString(m) }
func (*MutationResponse) ProtoMessage()    {}
func (*MutationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3cfc32bb50cc571, []int{13}
}
func (m *MutationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutationResponse.Unmarshal(m, b)
}
func (m *MutationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutationResponse.Marshal(b, m, deterministic)
}
func (m *MutationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutationResponse.Merge(m, src)
}
func (m *MutationResponse) XXX_Size() int {
	return xxx_messageInfo_MutationResponse.Size(m)
}
func (m *MutationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MutationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MutationResponse proto.InternalMessageInfo

func (m *MutationResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Mutation struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields               []*MutationField `protobuf:"bytes,8,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Mutation) Reset()         { *m = Mutation{} }
func (m *Mutation) String() string { return proto.CompactTextString(m) }
func (*Mutation) ProtoMessage()    {}
func (*Mutation) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3cfc32bb50cc571, []int{14}
}
func (m *Mutation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mutation.Unmarshal(m, b)
}
func (m *Mutation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mutation.Marshal(b, m, deterministic)
}
func (m *Mutation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mutation.Merge(m, src)
}
func (m *Mutation) XXX_Size() int {
	return xxx_messageInfo_Mutation.Size(m)
}
func (m *Mutation) XXX_DiscardUnknown() {
	xxx_messageInfo_Mutation.DiscardUnknown(m)
}

var xxx_messageInfo_Mutation proto.InternalMessageInfo

func (m *Mutation) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Mutation) GetFields() []*MutationField {
	if m != nil {
		return m.Fields
	}
	return nil
}

var E_Opts = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*SqlxMessageOptions)(nil),
	Field:         99901,
	Name:          "sql.opts",
	Tag:           "bytes,99901,opt,name=opts",
	Filename:      "pb/sql/sql.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*SqlxFieldOptions)(nil),
	Field:         99902,
	Name:          "sql.field",
	Tag:           "bytes,99902,opt,name=field",
	Filename:      "pb/sql/sql.proto",
}

var E_Server = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*SqlxServiceOptions)(nil),
	Field:         99903,
	Name:          "sql.server",
	Tag:           "bytes,99903,opt,name=server",
	Filename:      "pb/sql/sql.proto",
}

var E_Method = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*SqlxMethodOptions)(nil),
	Field:         99904,
	Name:          "sql.method",
	Tag:           "bytes,99904,opt,name=method",
	Filename:      "pb/sql/sql.proto",
}

func init() {
	proto.RegisterEnum("sql.SortCriteria_Order", SortCriteria_Order_name, SortCriteria_Order_value)
	proto.RegisterEnum("sql.Filter_Mode", Filter_Mode_name, Filter_Mode_value)
	proto.RegisterType((*ExtraField)(nil), "sql.ExtraField")
	proto.RegisterType((*SqlxMessageOptions)(nil), "sql.SqlxMessageOptions")
	proto.RegisterType((*SqlxFieldOptions)(nil), "sql.SqlxFieldOptions")
	proto.RegisterType((*SqlxServiceOptions)(nil), "sql.SqlxServiceOptions")
	proto.RegisterType((*SqlxMethodOptions)(nil), "sql.SqlxMethodOptions")
	proto.RegisterType((*SortCriteria)(nil), "sql.SortCriteria")
	proto.RegisterType((*Sorting)(nil), "sql.Sorting")
	proto.RegisterType((*Filter)(nil), "sql.Filter")
	proto.RegisterType((*PageInfo)(nil), "sql.PageInfo")
	proto.RegisterType((*Query)(nil), "sql.Query")
	proto.RegisterType((*Response)(nil), "sql.Response")
	proto.RegisterType((*ResponseList)(nil), "sql.ResponseList")
	proto.RegisterType((*MutationField)(nil), "sql.MutationField")
	proto.RegisterType((*MutationResponse)(nil), "sql.MutationResponse")
	proto.RegisterType((*Mutation)(nil), "sql.Mutation")
	proto.RegisterExtension(E_Opts)
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_Server)
	proto.RegisterExtension(E_Method)
}

func init() { proto.RegisterFile("pb/sql/sql.proto", fileDescriptor_f3cfc32bb50cc571) }

var fileDescriptor_f3cfc32bb50cc571 = []byte{
	// 980 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x55, 0xcd, 0x6e, 0xdb, 0xc6,
	0x13, 0x37, 0x45, 0x89, 0xa2, 0xc7, 0x4e, 0xfe, 0xcc, 0xe2, 0x5f, 0x97, 0x08, 0x50, 0xd7, 0x60,
	0x5b, 0x20, 0x09, 0x60, 0xa9, 0x75, 0x4f, 0x75, 0x4f, 0x8d, 0x2b, 0xd7, 0x01, 0xfc, 0x11, 0xaf,
	0xdc, 0x4b, 0x2f, 0x01, 0x25, 0x2e, 0x99, 0xad, 0x29, 0x2e, 0xb5, 0xbb, 0x74, 0x9c, 0x3e, 0x43,
	0xdf, 0xa4, 0xaf, 0xd0, 0xaf, 0x63, 0x5f, 0xa7, 0x6f, 0x50, 0xec, 0xec, 0x52, 0xa6, 0xa0, 0x1c,
	0x84, 0x9d, 0xdf, 0xcc, 0x70, 0x34, 0x33, 0xbf, 0xd9, 0x59, 0x88, 0xea, 0xd9, 0x58, 0x2d, 0x4b,
	0xf3, 0x1b, 0xd5, 0x52, 0x68, 0x41, 0x7c, 0xb5, 0x2c, 0x9f, 0x1e, 0x14, 0x42, 0x14, 0x25, 0x1b,
	0xa3, 0x6a, 0xd6, 0xe4, 0xe3, 0x8c, 0xa9, 0xb9, 0xe4, 0xb5, 0x16, 0xd2, 0xba, 0x25, 0x67, 0x00,
	0x93, 0x7b, 0x2d, 0xd3, 0x53, 0xce, 0xca, 0x8c, 0x10, 0xe8, 0xeb, 0xf7, 0x35, 0x8b, 0xbd, 0x03,
	0xef, 0xd9, 0x36, 0x45, 0xd9, 0xe8, 0xaa, 0x74, 0xc1, 0xe2, 0x9e, 0xd5, 0x19, 0x19, 0xfd, 0xd2,
	0x42, 0xc5, 0xbe, 0xf3, 0x4b, 0x0b, 0x95, 0xfc, 0xeb, 0x01, 0x99, 0x2e, 0xcb, 0xfb, 0x0b, 0xa6,
	0x54, 0x5a, 0xb0, 0xab, 0x5a, 0x73, 0x51, 0x29, 0x12, 0x81, 0x2f, 0xe4, 0x02, 0x23, 0x86, 0xd4,
	0x88, 0xe4, 0xff, 0x30, 0xf8, 0x59, 0x89, 0x6a, 0x86, 0x11, 0x43, 0x6a, 0x81, 0x09, 0x59, 0x18,
	0x47, 0x1f, 0x95, 0x28, 0x1b, 0x4f, 0x9d, 0xce, 0x4a, 0x16, 0xf7, 0xf1, 0x7f, 0x2c, 0x20, 0x7b,
	0x10, 0x64, 0x92, 0xdf, 0x31, 0x19, 0x0f, 0x50, 0xed, 0x10, 0x79, 0x0e, 0x43, 0x5e, 0xcd, 0xcb,
	0x26, 0x63, 0x71, 0x70, 0xe0, 0x3f, 0xdb, 0x39, 0xfa, 0xdf, 0xc8, 0xb4, 0xe3, 0xa1, 0x3c, 0xda,
	0xda, 0x49, 0x0c, 0x43, 0xc9, 0x96, 0x0d, 0x53, 0x3a, 0x1e, 0x62, 0x8c, 0x16, 0x9a, 0x34, 0x1a,
	0xc5, 0x64, 0x1c, 0xda, 0x34, 0x8c, 0x6c, 0xbc, 0x6b, 0x29, 0xb2, 0x66, 0xae, 0xe3, 0x6d, 0x54,
	0xb7, 0x30, 0xf9, 0xdd, 0x83, 0xc8, 0xd4, 0x8c, 0xe1, 0xdb, 0x8a, 0xdb, 0x86, 0x79, 0x9d, 0x86,
	0xc5, 0x30, 0x9c, 0x8b, 0xb2, 0xd3, 0xc7, 0x16, 0xae, 0x5a, 0xee, 0xaf, 0xb7, 0x1c, 0xdb, 0xdb,
	0x7f, 0x68, 0xaf, 0xd1, 0x65, 0x52, 0xd4, 0x58, 0x73, 0x48, 0x51, 0x26, 0x8f, 0xa1, 0x57, 0xdf,
	0xc6, 0x01, 0x6a, 0x7a, 0xf5, 0xad, 0xc1, 0xf9, 0xad, 0xab, 0xa8, 0x97, 0xdf, 0x92, 0x7d, 0x80,
	0x79, 0xa3, 0xb4, 0x58, 0xe0, 0x1f, 0x87, 0xa8, 0xef, 0x68, 0x92, 0x91, 0x65, 0x6c, 0xca, 0xe4,
	0x1d, 0x9f, 0xaf, 0x18, 0x8b, 0x61, 0x98, 0x36, 0x5a, 0x14, 0xac, 0x72, 0xac, 0xb5, 0x30, 0x79,
	0x0e, 0x4f, 0x2c, 0xc3, 0xfa, 0xad, 0x58, 0x95, 0xbb, 0xa2, 0xd3, 0xeb, 0xd0, 0x99, 0xdc, 0xc2,
	0xee, 0x54, 0x48, 0x7d, 0x22, 0xb9, 0x66, 0x92, 0xa7, 0x66, 0x0c, 0x74, 0x5a, 0xb8, 0x9e, 0x18,
	0x91, 0x1c, 0xc2, 0x40, 0xc8, 0x8c, 0x49, 0x6c, 0xc8, 0xe3, 0xa3, 0x8f, 0x91, 0xac, 0xee, 0x37,
	0xa3, 0x2b, 0x63, 0xa6, 0xd6, 0x2b, 0x79, 0x0a, 0x03, 0xc4, 0x64, 0x08, 0xfe, 0x77, 0xd3, 0x93,
	0x68, 0x8b, 0x84, 0xd0, 0xff, 0x7e, 0x32, 0x3d, 0x89, 0xbc, 0xe4, 0x4b, 0x18, 0x9a, 0x0f, 0x79,
	0x55, 0x90, 0x2f, 0xa0, 0xaf, 0x84, 0xd4, 0xb1, 0x87, 0x13, 0xf0, 0x64, 0x23, 0x28, 0x45, 0x73,
	0xf2, 0x9b, 0x07, 0xc1, 0x29, 0x2f, 0x35, 0x93, 0x1f, 0xa4, 0xeb, 0x73, 0xe8, 0x2f, 0x44, 0xc6,
	0x5c, 0x6a, 0x11, 0x46, 0xb1, 0xee, 0xa3, 0x0b, 0x91, 0x31, 0x8a, 0x56, 0x53, 0xf9, 0x5d, 0x5a,
	0x36, 0x2d, 0x77, 0x16, 0x24, 0xd7, 0xd0, 0x37, 0x3e, 0x24, 0x80, 0xde, 0xe4, 0x3a, 0xda, 0x32,
	0xe7, 0xe5, 0x24, 0xf2, 0xcc, 0xf9, 0xc3, 0x4d, 0xd4, 0xc3, 0x73, 0x12, 0xf9, 0xe6, 0x3c, 0xbf,
	0x89, 0xfa, 0x78, 0x4e, 0xa2, 0x01, 0xd9, 0x81, 0xe1, 0xab, 0xe9, 0x9b, 0xcb, 0x1f, 0xcf, 0xcf,
	0xa3, 0x80, 0xec, 0x42, 0x78, 0x79, 0x75, 0x63, 0xd1, 0x30, 0xc9, 0x21, 0x7c, 0x9d, 0x16, 0xec,
	0x55, 0x95, 0x0b, 0x9c, 0xa4, 0x46, 0x4a, 0x56, 0x69, 0xcc, 0xd8, 0xa7, 0x2d, 0x34, 0x85, 0x28,
	0xfe, 0x8b, 0x4d, 0xda, 0xa7, 0x28, 0x9b, 0xbb, 0x22, 0xf2, 0x5c, 0x31, 0x8d, 0x39, 0xfa, 0xd4,
	0x21, 0x93, 0x7a, 0xc9, 0x17, 0x5c, 0xe3, 0x88, 0xf9, 0xd4, 0x82, 0xe4, 0x1f, 0x0f, 0x06, 0xd7,
	0x0d, 0x93, 0xef, 0xcd, 0x24, 0xf1, 0xcc, 0xb5, 0xa4, 0xc7, 0x33, 0x43, 0x1f, 0xcf, 0x54, 0xdc,
	0x3b, 0xf0, 0x0d, 0x7d, 0x3c, 0x33, 0xb4, 0xf7, 0xeb, 0xb4, 0xb0, 0xb5, 0xfb, 0x67, 0x5b, 0x14,
	0x11, 0xd9, 0x83, 0x41, 0xce, 0xa5, 0x72, 0x71, 0xcf, 0xb6, 0xa8, 0x85, 0xc6, 0xbb, 0x4c, 0x95,
	0xc6, 0xe9, 0x45, 0x6f, 0x83, 0x1e, 0xb2, 0x08, 0x3a, 0x59, 0x90, 0xcf, 0x20, 0xc8, 0xb1, 0xd7,
	0xf1, 0x10, 0x49, 0xdc, 0xe9, 0xb4, 0x9f, 0x3a, 0x93, 0xf9, 0x34, 0x37, 0x97, 0x2e, 0x0e, 0x31,
	0x25, 0x0b, 0x5e, 0x86, 0x10, 0xd4, 0xa9, 0x4c, 0x17, 0x2a, 0xd9, 0x87, 0x90, 0x32, 0x55, 0x8b,
	0x4a, 0xe1, 0x75, 0xca, 0x52, 0x9d, 0x62, 0x39, 0xbb, 0x14, 0xe5, 0x24, 0x83, 0xdd, 0xd6, 0x7e,
	0xce, 0xed, 0xbd, 0x77, 0x3e, 0x7e, 0xeb, 0x83, 0xeb, 0x47, 0xe8, 0xb4, 0x74, 0x1d, 0xb5, 0x80,
	0xbc, 0x80, 0x6d, 0x53, 0xea, 0x1b, 0x5e, 0xe5, 0x02, 0xab, 0xdf, 0x39, 0x7a, 0x84, 0x19, 0xb6,
	0x14, 0xd1, 0xb0, 0x76, 0x52, 0xf2, 0x0d, 0x3c, 0xba, 0x68, 0x74, 0x6a, 0x2e, 0xca, 0x6a, 0xc1,
	0x6e, 0x0c, 0xdb, 0x6a, 0x8c, 0x7a, 0xdd, 0x31, 0x4a, 0x20, 0x6a, 0x3f, 0x5d, 0x15, 0xf2, 0xc0,
	0x8a, 0x6f, 0x58, 0x49, 0x4e, 0x21, 0x6c, 0x7d, 0x36, 0x18, 0x7b, 0x61, 0xba, 0xc8, 0xca, 0x4c,
	0x61, 0x87, 0x76, 0x8e, 0x08, 0xe6, 0xb8, 0x96, 0x0d, 0x75, 0x1e, 0xc7, 0x97, 0xd0, 0x17, 0xb5,
	0x56, 0xe4, 0xd3, 0x91, 0x7d, 0x2f, 0x46, 0xed, 0x7b, 0x31, 0x5a, 0x5f, 0xe6, 0xf1, 0x1f, 0xbf,
	0x06, 0x58, 0xb0, 0xbb, 0xac, 0x1b, 0xdb, 0x9e, 0x62, 0x9c, 0xe3, 0x73, 0x47, 0x0e, 0xf9, 0x64,
	0x23, 0x60, 0x77, 0x53, 0xc6, 0x7f, 0xba, 0x70, 0x1f, 0xad, 0xc2, 0x75, 0xcd, 0x8e, 0xd4, 0x63,
	0x0a, 0x81, 0x62, 0xd2, 0x6c, 0xf8, 0xcd, 0xfc, 0xd6, 0x57, 0x57, 0xfc, 0xd7, 0x46, 0x7e, 0xeb,
	0x0e, 0xd4, 0x45, 0x3a, 0x7e, 0x0d, 0xc1, 0x02, 0xb7, 0x18, 0xd9, 0xff, 0x40, 0xcd, 0x9d, 0xf5,
	0x16, 0xff, 0xed, 0x42, 0xee, 0x75, 0x4a, 0xee, 0xd8, 0xa9, 0x8b, 0xf3, 0xf2, 0xab, 0x9f, 0xc6,
	0x05, 0xd7, 0x6f, 0x9b, 0xd9, 0x68, 0x2e, 0x16, 0xe3, 0x77, 0x8c, 0xbf, 0x13, 0xe5, 0x1d, 0x53,
	0xf6, 0xe9, 0x9d, 0x1f, 0x16, 0xac, 0x3a, 0x54, 0xcb, 0xf2, 0x7e, 0x6c, 0x1f, 0xea, 0x6f, 0xd5,
	0xb2, 0x9c, 0x05, 0x68, 0xfb, 0xfa, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x95, 0x15, 0x75, 0x07,
	0xbd, 0x07, 0x00, 0x00,
}
